instagram_clone/config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root   'top_pages#top_page'
  get    '/signup',  to: 'users#new'
  post   '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :pictures,        only: [:new, :create, :show, :update, :destroy]
  resources :relationships,   only: [:create, :destroy]
  resources :comments
end

instagram_clone/app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  before_action :get_user, only: [:edit, :update]
  before_action :logged_in_user, only: [:edit, :update]

  def new
  end

  def edit
  end

  def update
    if params[:user][:new_password].empty?
      flash[:danger] = "New password can't be empty!"
      render 'edit'
      return
    end

    if @user && @user.authenticate(params[:user][:password])
      if params[:user][:new_password] == params[:user][:password_confirmation]
        params[:user][:password] = params[:user][:new_password]
        @user.update_attributes(user_params)
        flash[:success] = "Password changed."
        redirect_to user_url(@user)
      else
        flash[:danger] = "new password and cofirmation are differente."
        render 'edit'
      end
    else
      flash[:danger] = "Current password is wrong."
      render 'edit'
    end
  end

  private
    def user_params
      params.require(:user).permit(:password)
    end

    #before_action
    def get_user
      @user = User.find(params[:id])
    end
end

instagram_clone/app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

instagram_clone/app/views/password_resets/edit.html.erb
<%= provide(:title, "Reset Password") %>
<h1>Reset Password</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: password_reset_path) do |f| %>

      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :current_password %>
      <%= f.password_field :password %>

      <%= f.label :new_password %>
      <%= f.password_field :new_password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Reset Password", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

instagram_clone/app/views/password_resets/new.html.erb
<h1>PasswordResets#new</h1>
<p>Find me in app/views/password_resets/new.html.erb</p>