instagram_clone/config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root   'top_pages#top_page'
  get    '/signup',  to: 'users#new'
  post   '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :pictures,        only: [:new, :create, :show, :update, :destroy]
  resources :relationships,   only: [:create, :destroy]
  resources :comments
end

instagram_clone/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :picture
  default_scope -> {order(created_at: :desc)}
  validates :user_id, presence: true
  validates :content, presence: true, length: {maximum: 250}
end

instagram_clone/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :logged_in_user, only: [:new, :create, :destroy]
  
  def new
    @comment = Picture.find_by(id: params[:id]).build
  end

  def show
    @picture = Picture.find_by(id: params[:id])
    @comments = @picture.comments
    @user = @picture.user
  end
  
  def create
    @comment = Picture.find_by(id: params[:id]).build
  end

  private
    def comment_params
      params.require(:comment).permit(:user_id, :content)
    end
end

instagram_clone/app/helpers/comments_helper.rb
module CommentsHelper
end

instagram_clone/app/views/comments/_comment.html.erb
<li id="comment-<%= comment.id %>">
  <span class="content"><%= comment.content %></span>
  <span class="user"><%= link_to @user.user_name, user_url(@user) %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(comment.created_at) %> ago.
  </span>
</li>

instagram_clone/app/views/comments/_show.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <%= image_tag @picture.picture.url %>
    Posted <%= time_ago_in_words(@picture.created_at) %> ago.
    <ol class="comments">
      <%= render @comments %>
    </ol>
  </div>
</div>

instagram_clone/app/views/comments/show.js.erb
$("#user-modal").html("<%= escape_javascript(render 'show') %>");
$("#user-modal").modal("show");