instagram_clone/config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root   'top_pages#top_page'
  get    '/signup',  to: 'users#new'
  post   '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :pictures,        only: [:new, :create, :show, :update, :destroy]
  resources :relationships,   only: [:create, :destroy]
  resources :comments
end

instagram_clone/app/models/user.rb
class User < ApplicationRecord
  has_many :pictures, dependent: :destroy
  has_many :active_relationships, class_name: "Relationship",
                                 foreign_key: "follower_id",
                                   dependent: :destroy
  has_many :passive_relationships,class_name: "Relationship",
                                 foreign_key: "followed_id",
                                   dependent: :destroy
  has_many :following, through: :active_relationships,  source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  before_save {self.email = email.downcase}
  #[TODO]URLエンコードがしたい
  #before_save {CGI.escape(self.web_site)}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  #[TODO]下記の正規表現ではPhone is invalid とエラーが出るが、解消方法がわからない
  #VALID_PHONE_REGEX = /\d+/
  validates :first_name, presence: true, length:{maximum:20}
  validates :last_name,  presence: true, length:{maximum:20}
  validates :user_name,  presence: true, length:{maximum:40}
  validates :email,      presence: true, length:{maximum:100},
                         format:{with:VALID_EMAIL_REGEX},
                         uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password,       presence: true, length: {minimum: 6}, allow_nil: true
  validates :self_introduce, length: {maximum: 500}
  #validates :phone,          format:{with:VALID_PHONE_REGEX}

  # 渡された文字列のハッシュ値を返す
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def follow(other_user)
    following << other_user
  end

  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # 渡されたユーザがログインしているユーザをフォローしていればtrue
  def following?(other_user)
    following.include?(other_user)
  end

  # ログイン中のユーザ自身とフォローしているユーザのpictureを返す
  def time_line
    following_ids = "SELECT followed_id FROM relationships WHERE
                     follower_id = :user_id"
    Picture.where("user_id IN (#{following_ids})
                   OR user_id = :user_id", user_id: id)
  end
end

instagram_clone/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update]

  def new
    @user = User.new
  end

  def index
    @users = User.where.not(id: current_user.id ).paginate(page:params[:page])
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in(@user)
      flash[:success] = "Welcome!"
      redirect_to user_url(@user)
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "updated!"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def show
    @user = User.find(params[:id])
    @pictures = @user.pictures.paginate(page: params[:page])
  end

  def destroy
    User.find(params[:id]).destroy
    log_out
    flash[:success] = "Thank you for using our service."
    redirect_to root_url
  end

  private
    def user_params
      params.require(:user).permit(:first_name, :last_name, :user_name,
                                   :email,
                                   :web_site, :self_introduce,
                                   :phone, :gender,
                                   :password,
                                   :password_confirmation)
    end

    # 正しいユーザーかどうか確認
    def correct_user
      @user = User.find(params[:id])
      unless current_user?(@user)
        flash[:danger] = "You have accessed a wrong path."
        redirect_to(root_path)
      end
    end
end

instagram_clone/app/helpers/users_helper.rb
module UsersHelper
end

instagram_clone/app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build) do |f| %>
  <div>
    <%= hidden_field_tag :followed_id, @user.id %>
  </div>
  <%= f.submit "follow", class: "btn btn-primary" %>
<% end %>

instagram_clone/app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: {method: :delete}) do |f| %>
  <%= f.submit "unfollow", class: "btn btn-primary" %>
<% end %>

instagram_clone/app/views/users/edit.html.erb
<% provide(:title, "Edit profile") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <p>Public User Informations</p>
      <%= f.label :name %>
      <%= f.text_field :first_name, placeholder: "first name" %>
      <%= f.text_field :last_name, placeholder: "last name" %>

      <%= f.label :user_name %>
      <%= f.text_field :user_name %>

      <%= f.label :web_site %>
      <%= f.text_field :web_site %>

      <%= f.label :introduce_your_self %>
      <%= f.text_field :self_introduce %>

      <p>Private User Informations</p>

      <%= f.label :email %>
      <%= f.email_field :email %>

      <%= f.label :phone %>
      <%= f.telephone_field :phone %>

      <%= f.label :male %>
      <%= f.radio_button 'gender', '1', {} %>
      <%= f.label :female %>
      <%= f.radio_button 'gender', '0', {} %>

      <%= f.submit "Save the Change", class: "btn btn-primary" %>

      <%= link_to "edit password", edit_password_reset_path, class: "btn btn-primary" %>
      <%= link_to "delete account", @user, method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

instagram_clone/app/views/users/index.html.erb
<% provide(:title, "People") %>
<h1>Find your friend</h1>

<%= will_paginate %>
  <% @users.each do |user| %>
    <li>
      <%= link_to user.user_name, user %>
    </li>
  <% end %>
<%= will_paginate %>

instagram_clone/app/views/users/new.html.erb
<% provide(:title, "Sign up") %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: signup_path) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <p>Public User Informations</p>
      <%= f.label :name %>
      <%= f.text_field :first_name, placeholder: "first name" %>
      <%= f.text_field :last_name, placeholder: "last name" %>
      
      <%= f.label :user_name %>
      <%= f.text_field :user_name %>

      <%= f.label :web_site %>
      <%= f.text_field :web_site %>

      <%= f.label :introduce_your_self %>
      <%= f.text_field :self_introduce %>

      <p>Private User Informations</p>

      <%= f.label :email %>
      <%= f.email_field :email %>

      <%= f.label :phone %>
      <%= f.telephone_field :phone %>

      <%= f.label :male %>
      <%= f.radio_button 'gender', '1', {} %>
      <%= f.label :female %>
      <%= f.radio_button 'gender', '0', {} %>

      <p>Pssword</p>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

instagram_clone/app/views/users/show.html.erb
<% provide(:title, "User Page") %>
<% if current_user == @user %>
  <h1>Hi, <%= @user.first_name %>!</h1>
  <div>
    <label for="name">Self introduce<label>
    <textarea readonly>
      <%= @user.self_introduce %>
    </textarea>
  </div>
  <%= link_to "update my info", edit_user_path, class: "btn btn-primary"%>
<% else %>
  <h1><%= @user.user_name %>'s page</h1>
  <div>
    <label for="name">Self introduce<label>
    <textarea readonly>
      <%= @user.self_introduce %>
    </textarea>
  </div>
  <% unless current_user?(@user) %>
    <div id="follow_form">
      <% if current_user.following?(@user) %>
        <%= render 'unfollow' %>
      <% else %>
      <%= render 'follow' %>
      <% end %>
    </div>
  <% end %>
<% end %>

<div class="row">
  <div class="col-md-8">
    <% if @user.pictures.any? %>
      <h3>Pictures (<%= @user.pictures.count %>)</h3>
      <ol class="pictures">
        <%= render @pictures %>
      </ol>
      <%= will_paginate @pictures %>
    <% end %>
  </div>
</div>